commerce_payment.commerce_payment_gateway.plugin.elavon_onsite:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant Id'
    user_id:
      type: string
      label: 'Merchant User Id'
    pin:
      type: string
      label: 'Merchant Pin'
    multicurrency:
      type: boolean
      label: "Multi-Currency support"

commerce_payment.commerce_payment_gateway.plugin.elavon_offsite_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant Id'
    user_id:
      type: string
      label: 'Merchant User Id'
    pin:
      type: string
      label: 'Merchant Pin'
    multicurrency:
      type: boolean
      label: "Multi-Currency support"
